<?xml version="1.0"?>
<project name="HomologyMapper" default="jar" basedir=".">

	<property name="src.dir" value="src"/>
	<property name="lib.dir" value="lib"/>
	<property name="build.dir" value="build"/>
	<property name="jar.name" value="${ant.project.name}.jar"/>
	<property name="dist.dir" value="dist"/>
	
	<path id="project.class.path">
		<fileset dir="${lib.dir}">
			<include name="derby.jar"/>
			<include name="org.bridgedb-3.0.30.jar"/>
                        <include name="org.bridgedb.bio-3.0.30.jar"/>
                        <include name="org.bridgedb.rdb-3.0.30.jar"/>
			<include name="org.pathvisio.core.jar"/>
                        <include name="com.springsource.org.jdom-2.0.1.jar"/>
		</fileset>
	</path>
	
	<target name="clean">
		<delete dir="${build.dir}"/>
		<delete dir="${dist.dir}"/>
		<delete dir="bin"/>
	</target>
	
	<target name="prepare">
		<mkdir dir="${build.dir}"/>
		<mkdir dir="${dist.dir}/lib"/>
		<copy todir="${dist.dir}/lib">
   			<fileset dir="${lib.dir}"/>
 		</copy>
	</target>
	
	<target name="compile" depends="prepare">
		<echo>Compiling: ${jar.name}</echo>
		<javac srcdir="${src.dir}" includes="**" destdir="${build.dir}" debug="true">
			<classpath refid="project.class.path"/>
		</javac>
	</target>
	
	<target name="jar" depends="compile"> 
		<echo>Creating JAR: ${jar.name}</echo>
		<jar jarfile="${dist.dir}/${jar.name}">
			<manifest>
               			<attribute name="Main-Class" value="org.wp.homology.LocalHomologyConverter"/>
				<attribute name="Class-Path" value="lib/derby.jar lib/org.bridgedb-3.0.30.jar lib/org.bridgedb.bio-3.0.30.jar lib/org.bridgedb.rdb-3.0.30.jar lib/org.pathvisio.core.jar lib/com.springsource.org.jdom-2.0.1.jar"/>
            		</manifest>
			<fileset dir="build">
				<include name="**/*"/>					
			</fileset>
		</jar>
	</target>
</project>
